import os 
import numpy as np
from groq import Groq
from dotenv import load_dotenv

class RAG:
    def __init__(self, db, k=2):
        load_dotenv()
        self.db = db
        self.index = self.db.embed_documents()
        self.k = k
        self.embed_model = self.db.model
        self.model = os.getenv("MODEL_NAME")
        self.client = Groq(api_key=os.getenv("GROQ_API"))
        
    def retrieve(self, query):
        """
        Encodes the query as an embedding and searches the index for the k documents
        closest by similarity.

        Returns:
        - docs: list of candidate document contents,
        - distances: associated distances (to evaluate similarity).
        """
        query_embedding = self.embed_model.encode([query])
        distances, indices = self.index.search(
            np.array(query_embedding, dtype=np.float32), self.k
        )
        docs = [self.db.documents[i].page_content for i in indices[0]]
        return docs, distances
    
    def generate_answer(self, query):
        """
        Generates an augmented response:
        - Encodes the query with Sentence Transformers,
        - Retrieves the k candidate documents,
        - Constructs a prompt integrating the context (the retrieved documents) and the question,
        - Sends the prompt to the LLM via Groq to obtain a response.

        Returns:
        - answer: the response generated by the LLM,
        - retrieved_docs: list of candidate documents,
        - distances: distances associated with the retrieved documents.
        """
        retrieved_docs, distances = self.retrieve(query)
        context = " ".join(retrieved_docs)
        prompt = f"Context: {context}\nQuestion: {query}\nAnswer:"
        answer = self.client.chat.completions.create(
            messages = [
                {
                    "role": "user",
                    "content": prompt
                }

            ],
            model = self.model,
            max_tokens = 500
        )
        
        return answer.choices[0].message.content.strip(), retrieved_docs, distances
